### ISSUE TITLE
cannot import  seplut_ext

### ISSUE THREAD

**Issue by BeyondHeaven** [ImCharlesY/SepLUT#5]
I cannot import  seplut_ext. Do you know anything about it? Thanks!
I install torch1.8.0 and mmcv1.6.0 successfully.
```
  Traceback (most recent call last):
  File "/local/mnt/workspace/testcode/miniconda3/envs/python38/lib/python3.8/site-packages/mmcv/utils/misc.py", line 73, in import_module
s_from_strings
    imported_tmp = import_module(imp)
  File "/local/mnt/workspace/testcode/miniconda3/envs/python38/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/local/mnt/workspace/testcode/SepLUT/seplut/__init__.py", line 1, in <module>
    from .model import SepLUT
  File "/local/mnt/workspace/testcode/SepLUT/seplut/model.py", line 25, in <module>
    from seplut_ext import seplut_transform
  File "/local/mnt/workspace/testcode/miniconda3/envs/python38/lib/python3.8/site-packages/seplut_ext-1.2.0-py3.8-linux-x86_64.egg/seplut_ext/__init__.py", line 1, in <module>
    from .pyinterfaces import seplut_transform
  File "/local/mnt/workspace/testcode/miniconda3/envs/python38/lib/python3.8/site-packages/seplut_ext-1.2.0-py3.8-linux-x86_64.egg/seplut_ext/pyinterfaces.py", line 6, in <module>
    from ._ext import cforward
ImportError: /local/mnt/workspace/testcode/miniconda3/envs/python38/lib/python3.8/site-packages/seplut_ext-1.2.0-py3.8-linux-x86_64.egg/seplut_ext/_ext.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN3c104impl8GPUTrace13gpuTraceStateE

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 169, in <module>
    main()
  File "tools/train.py", line 76, in main
    cfg = Config.fromfile(args.config)
  File "/local/mnt/workspace/testcode/miniconda3/envs/python38/lib/python3.8/site-packages/mmcv/utils/config.py", line 343, in fromfile
    import_modules_from_strings(**cfg_dict['custom_imports'])
  File "/local/mnt/workspace/testcode/miniconda3/envs/python38/lib/python3.8/site-packages/mmcv/utils/misc.py", line 80, in import_modules_from_strings
    raise ImportError
ImportError
```

**Comment by LYL1015** [comment]
Hey, I had the same problem. Did you solve it?

**Comment by Liptee** [comment]
> Hey, I had the same problem. Did you solve it?

It's been a while, but I'm stuck in same issue. Maybe you can solve it?

**Comment by qianyisharon** [comment]
I have the same problem, Did you solve it ?

**Comment by BertonYang18** [comment]
> I have the same problem, Did you solve it ?

You can locate < seplut/model.py  line-25 >
ori:
from seplut_ext import seplut_transform
modify to:
from seplut import seplut_transform
